/*
    Data taken from: (November 19, 2021)
    https://raw.githubusercontent.com/lukes/ISO-3166-Countries-with-Regional-Codes/master/all/all.json
*/

let countriesAndCodes = [
    { 
        name: "Afghanistan", 
        "alpha-2": "AF", 
        "country-code": "004", 
        region: "Asia" 
    },
    { name: "Åland Islands", "alpha-2": "AX", "country-code": "248", region: "Europe" },
    { name: "Albania", "alpha-2": "AL", "country-code": "008", region: "Europe" },
    { name: "Algeria", "alpha-2": "DZ", "country-code": "012", region: "Africa" },
    { name: "American Samoa", "alpha-2": "AS", "country-code": "016", region: "Oceania" },
    { name: "Andorra", "alpha-2": "AD", "country-code": "020", region: "Europe" },
    { name: "Angola", "alpha-2": "AO", "country-code": "024", region: "Africa" },
    { name: "Anguilla", "alpha-2": "AI", "country-code": "660", region: "Americas" },
    { name: "Antarctica", "alpha-2": "AQ", "country-code": "010", region: "" },
    { name: "Antigua and Barbuda", "alpha-2": "AG", "country-code": "028", region: "Americas" },
    { name: "Argentina", "alpha-2": "AR", "country-code": "032", region: "Americas" },
    { name: "Armenia", "alpha-2": "AM", "country-code": "051", region: "Asia" },
    { name: "Aruba", "alpha-2": "AW", "country-code": "533", region: "Americas" },
    { name: "Australia", "alpha-2": "AU", "country-code": "036", region: "Oceania" },
    { name: "Austria", "alpha-2": "AT", "country-code": "040", region: "Europe" },
    { name: "Azerbaijan", "alpha-2": "AZ", "country-code": "031", region: "Asia" },
    { name: "Bahamas", "alpha-2": "BS", "country-code": "044", region: "Americas" },
    { name: "Bahrain", "alpha-2": "BH", "country-code": "048", region: "Asia" },
    { name: "Bangladesh", "alpha-2": "BD", "country-code": "050", region: "Asia" },
    { name: "Barbados", "alpha-2": "BB", "country-code": "052", region: "Americas" },
    { name: "Belarus", "alpha-2": "BY", "country-code": "112", region: "Europe" },
    { name: "Belgium", "alpha-2": "BE", "country-code": "056", region: "Europe" },
    { name: "Belize", "alpha-2": "BZ", "country-code": "084", region: "Americas" },
    { name: "Benin", "alpha-2": "BJ", "country-code": "204", region: "Africa" },
    { name: "Bermuda", "alpha-2": "BM", "country-code": "060", region: "Americas" },
    { name: "Bhutan", "alpha-2": "BT", "country-code": "064", region: "Asia" },
    { name: "Bolivia (Plurinational State of)", "alpha-2": "BO", "country-code": "068", region: "Americas" },
    { name: "Bonaire, Sint Eustatius and Saba", "alpha-2": "BQ", "country-code": "535", region: "Americas" },
    { name: "Bosnia and Herzegovina", "alpha-2": "BA", "country-code": "070", region: "Europe" },
    { name: "Botswana", "alpha-2": "BW", "country-code": "072", region: "Africa" },
    { name: "Bouvet Island", "alpha-2": "BV", "country-code": "074", region: "Americas" },
    { name: "Brazil", "alpha-2": "BR", "country-code": "076", region: "Americas" },
    { name: "British Indian Ocean Territory", "alpha-2": "IO", "country-code": "086", region: "Africa" },
    { name: "Brunei Darussalam", "alpha-2": "BN", "country-code": "096", region: "Asia" },
    { name: "Bulgaria", "alpha-2": "BG", "country-code": "100", region: "Europe" },
    { name: "Burkina Faso", "alpha-2": "BF", "country-code": "854", region: "Africa" },
    { name: "Burundi", "alpha-2": "BI", "country-code": "108", region: "Africa" },
    { name: "Cabo Verde", "alpha-2": "CV", "country-code": "132", region: "Africa" },
    { name: "Cambodia", "alpha-2": "KH", "country-code": "116", region: "Asia" },
    { name: "Cameroon", "alpha-2": "CM", "country-code": "120", region: "Africa" },
    { name: "Canada", "alpha-2": "CA", "country-code": "124", region: "Americas" },
    { name: "Cayman Islands", "alpha-2": "KY", "country-code": "136", region: "Americas" },
    { name: "Central African Republic", "alpha-2": "CF", "country-code": "140", region: "Africa" },
    { name: "Chad", "alpha-2": "TD", "country-code": "148", region: "Africa" },
    { name: "Chile", "alpha-2": "CL", "country-code": "152", region: "Americas" },
    { name: "China", "alpha-2": "CN", "country-code": "156", region: "Asia" },
    { name: "Christmas Island", "alpha-2": "CX", "country-code": "162", region: "Oceania" },
    { name: "Cocos (Keeling) Islands", "alpha-2": "CC", "country-code": "166", region: "Oceania" },
    { name: "Colombia", "alpha-2": "CO", "country-code": "170", region: "Americas" },
    { name: "Comoros", "alpha-2": "KM", "country-code": "174", region: "Africa" },
    { name: "Congo", "alpha-2": "CG", "country-code": "178", region: "Africa" },
    { name: "Congo, Democratic Republic of the", "alpha-2": "CD", "country-code": "180", region: "Africa" },
    { name: "Cook Islands", "alpha-2": "CK", "country-code": "184", region: "Oceania" },
    { name: "Costa Rica", "alpha-2": "CR", "country-code": "188", region: "Americas" },
    { name: "Côte d'Ivoire", "alpha-2": "CI", "country-code": "384", region: "Africa" },
    { name: "Croatia", "alpha-2": "HR", "country-code": "191", region: "Europe" },
    { name: "Cuba", "alpha-2": "CU", "country-code": "192", region: "Americas" },
    { name: "Curaçao", "alpha-2": "CW", "country-code": "531", region: "Americas" },
    { name: "Cyprus", "alpha-2": "CY", "country-code": "196", region: "Asia" },
    { name: "Czechia", "alpha-2": "CZ", "country-code": "203", region: "Europe" },
    { name: "Denmark", "alpha-2": "DK", "country-code": "208", region: "Europe" },
    { name: "Djibouti", "alpha-2": "DJ", "country-code": "262", region: "Africa" },
    { name: "Dominica", "alpha-2": "DM", "country-code": "212", region: "Americas" },
    { name: "Dominican Republic", "alpha-2": "DO", "country-code": "214", region: "Americas" },
    { name: "Ecuador", "alpha-2": "EC", "country-code": "218", region: "Americas" },
    { name: "Egypt", "alpha-2": "EG", "country-code": "818", region: "Africa" },
    { name: "El Salvador", "alpha-2": "SV", "country-code": "222", region: "Americas" },
    { name: "Equatorial Guinea", "alpha-2": "GQ", "country-code": "226", region: "Africa" },
    { name: "Eritrea", "alpha-2": "ER", "country-code": "232", region: "Africa" },
    { name: "Estonia", "alpha-2": "EE", "country-code": "233", region: "Europe" },
    { name: "Eswatini", "alpha-2": "SZ", "country-code": "748", region: "Africa" },
    { name: "Ethiopia", "alpha-2": "ET", "country-code": "231", region: "Africa" },
    { name: "Falkland Islands (Malvinas)", "alpha-2": "FK", "country-code": "238", region: "Americas" },
    { name: "Faroe Islands", "alpha-2": "FO", "country-code": "234", region: "Europe" },
    { name: "Fiji", "alpha-2": "FJ", "country-code": "242", region: "Oceania" },
    { name: "Finland", "alpha-2": "FI", "country-code": "246", region: "Europe" },
    { name: "France", "alpha-2": "FR", "country-code": "250", region: "Europe" },
    { name: "French Guiana", "alpha-2": "GF", "country-code": "254", region: "Americas" },
    { name: "French Polynesia", "alpha-2": "PF", "country-code": "258", region: "Oceania" },
    { name: "French Southern Territories", "alpha-2": "TF", "country-code": "260", region: "Africa" },
    { name: "Gabon", "alpha-2": "GA", "country-code": "266", region: "Africa" },
    { name: "Gambia", "alpha-2": "GM", "country-code": "270", region: "Africa" },
    { name: "Georgia", "alpha-2": "GE", "country-code": "268", region: "Asia" },
    { name: "Germany", "alpha-2": "DE", "country-code": "276", region: "Europe" },
    { name: "Ghana", "alpha-2": "GH", "country-code": "288", region: "Africa" },
    { name: "Gibraltar", "alpha-2": "GI", "country-code": "292", region: "Europe" },
    { name: "Greece", "alpha-2": "GR", "country-code": "300", region: "Europe" },
    { name: "Greenland", "alpha-2": "GL", "country-code": "304", region: "Americas" },
    { name: "Grenada", "alpha-2": "GD", "country-code": "308", region: "Americas" },
    { name: "Guadeloupe", "alpha-2": "GP", "country-code": "312", region: "Americas" },
    { name: "Guam", "alpha-2": "GU", "country-code": "316", region: "Oceania" },
    { name: "Guatemala", "alpha-2": "GT", "country-code": "320", region: "Americas" },
    { name: "Guernsey", "alpha-2": "GG", "country-code": "831", region: "Europe" },
    { name: "Guinea", "alpha-2": "GN", "country-code": "324", region: "Africa" },
    { name: "Guinea-Bissau", "alpha-2": "GW", "country-code": "624", region: "Africa" },
    { name: "Guyana", "alpha-2": "GY", "country-code": "328", region: "Americas" },
    { name: "Haiti", "alpha-2": "HT", "country-code": "332", region: "Americas" },
    { name: "Heard Island and McDonald Islands", "alpha-2": "HM", "country-code": "334", region: "Oceania" },
    { name: "Holy See", "alpha-2": "VA", "country-code": "336", region: "Europe" },
    { name: "Honduras", "alpha-2": "HN", "country-code": "340", region: "Americas" },
    { name: "Hong Kong", "alpha-2": "HK", "country-code": "344", region: "Asia" },
    { name: "Hungary", "alpha-2": "HU", "country-code": "348", region: "Europe" },
    { name: "Iceland", "alpha-2": "IS", "country-code": "352", region: "Europe" },
    { name: "India", "alpha-2": "IN", "country-code": "356", region: "Asia" },
    { name: "Indonesia", "alpha-2": "ID", "country-code": "360", region: "Asia" },
    { name: "Iran (Islamic Republic of)", "alpha-2": "IR", "country-code": "364", region: "Asia" },
    { name: "Iraq", "alpha-2": "IQ", "country-code": "368", region: "Asia" },
    { name: "Ireland", "alpha-2": "IE", "country-code": "372", region: "Europe" },
    { name: "Isle of Man", "alpha-2": "IM", "country-code": "833", region: "Europe" },
    { name: "Israel", "alpha-2": "IL", "country-code": "376", region: "Asia" },
    { name: "Italy", "alpha-2": "IT", "country-code": "380", region: "Europe" },
    { name: "Jamaica", "alpha-2": "JM", "country-code": "388", region: "Americas" },
    { name: "Japan", "alpha-2": "JP", "country-code": "392", region: "Asia" },
    { name: "Jersey", "alpha-2": "JE", "country-code": "832", region: "Europe" },
    { name: "Jordan", "alpha-2": "JO", "country-code": "400", region: "Asia" },
    { name: "Kazakhstan", "alpha-2": "KZ", "country-code": "398", region: "Asia" },
    { name: "Kenya", "alpha-2": "KE", "country-code": "404", region: "Africa" },
    { name: "Kiribati", "alpha-2": "KI", "country-code": "296", region: "Oceania" },
    { name: "Korea (Democratic People's Republic of)", "alpha-2": "KP", "country-code": "408", region: "Asia" },
    { name: "Korea, Republic of", "alpha-2": "KR", "country-code": "410", region: "Asia" },
    { name: "Kuwait", "alpha-2": "KW", "country-code": "414", region: "Asia" },
    { name: "Kyrgyzstan", "alpha-2": "KG", "country-code": "417", region: "Asia" },
    { name: "Lao People's Democratic Republic", "alpha-2": "LA", "country-code": "418", region: "Asia" },
    { name: "Latvia", "alpha-2": "LV", "country-code": "428", region: "Europe" },
    { name: "Lebanon", "alpha-2": "LB", "country-code": "422", region: "Asia" },
    { name: "Lesotho", "alpha-2": "LS", "country-code": "426", region: "Africa" },
    { name: "Liberia", "alpha-2": "LR", "country-code": "430", region: "Africa" },
    { name: "Libya", "alpha-2": "LY", "country-code": "434", region: "Africa" },
    { name: "Liechtenstein", "alpha-2": "LI", "country-code": "438", region: "Europe" },
    { name: "Lithuania", "alpha-2": "LT", "country-code": "440", region: "Europe" },
    { name: "Luxembourg", "alpha-2": "LU", "country-code": "442", region: "Europe" },
    { name: "Macao", "alpha-2": "MO", "country-code": "446", region: "Asia" },
    { name: "Madagascar", "alpha-2": "MG", "country-code": "450", region: "Africa" },
    { name: "Malawi", "alpha-2": "MW", "country-code": "454", region: "Africa" },
    { name: "Malaysia", "alpha-2": "MY", "country-code": "458", region: "Asia" },
    { name: "Maldives", "alpha-2": "MV", "country-code": "462", region: "Asia" },
    { name: "Mali", "alpha-2": "ML", "country-code": "466", region: "Africa" },
    { name: "Malta", "alpha-2": "MT", "country-code": "470", region: "Europe" },
    { name: "Marshall Islands", "alpha-2": "MH", "country-code": "584", region: "Oceania" },
    { name: "Martinique", "alpha-2": "MQ", "country-code": "474", region: "Americas" },
    { name: "Mauritania", "alpha-2": "MR", "country-code": "478", region: "Africa" },
    { name: "Mauritius", "alpha-2": "MU", "country-code": "480", region: "Africa" },
    { name: "Mayotte", "alpha-2": "YT", "country-code": "175", region: "Africa" },
    { name: "Mexico", "alpha-2": "MX", "country-code": "484", region: "Americas" },
    { name: "Micronesia (Federated States of)", "alpha-2": "FM", "country-code": "583", region: "Oceania" },
    { name: "Moldova, Republic of", "alpha-2": "MD", "country-code": "498", region: "Europe" },
    { name: "Monaco", "alpha-2": "MC", "country-code": "492", region: "Europe" },
    { name: "Mongolia", "alpha-2": "MN", "country-code": "496", region: "Asia" },
    { name: "Montenegro", "alpha-2": "ME", "country-code": "499", region: "Europe" },
    { name: "Montserrat", "alpha-2": "MS", "country-code": "500", region: "Americas" },
    { name: "Morocco", "alpha-2": "MA", "country-code": "504", region: "Africa" },
    { name: "Mozambique", "alpha-2": "MZ", "country-code": "508", region: "Africa" },
    { name: "Myanmar", "alpha-2": "MM", "country-code": "104", region: "Asia" },
    { name: "Namibia", "alpha-2": "NA", "country-code": "516", region: "Africa" },
    { name: "Nauru", "alpha-2": "NR", "country-code": "520", region: "Oceania" },
    { name: "Nepal", "alpha-2": "NP", "country-code": "524", region: "Asia" },
    { name: "Netherlands", "alpha-2": "NL", "country-code": "528", region: "Europe" },
    { name: "New Caledonia", "alpha-2": "NC", "country-code": "540", region: "Oceania" },
    { name: "New Zealand", "alpha-2": "NZ", "country-code": "554", region: "Oceania" },
    { name: "Nicaragua", "alpha-2": "NI", "country-code": "558", region: "Americas" },
    { name: "Niger", "alpha-2": "NE", "country-code": "562", region: "Africa" },
    { name: "Nigeria", "alpha-2": "NG", "country-code": "566", region: "Africa" },
    { name: "Niue", "alpha-2": "NU", "country-code": "570", region: "Oceania" },
    { name: "Norfolk Island", "alpha-2": "NF", "country-code": "574", region: "Oceania" },
    { name: "North Macedonia", "alpha-2": "MK", "country-code": "807", region: "Europe" },
    { name: "Northern Mariana Islands", "alpha-2": "MP", "country-code": "580", region: "Oceania" },
    { name: "Norway", "alpha-2": "NO", "country-code": "578", region: "Europe" },
    { name: "Oman", "alpha-2": "OM", "country-code": "512", region: "Asia" },
    { name: "Pakistan", "alpha-2": "PK", "country-code": "586", region: "Asia" },
    { name: "Palau", "alpha-2": "PW", "country-code": "585", region: "Oceania" },
    { name: "Palestine, State of", "alpha-2": "PS", "country-code": "275", region: "Asia" },
    { name: "Panama", "alpha-2": "PA", "country-code": "591", region: "Americas" },
    { name: "Papua New Guinea", "alpha-2": "PG", "country-code": "598", region: "Oceania" },
    { name: "Paraguay", "alpha-2": "PY", "country-code": "600", region: "Americas" },
    { name: "Peru", "alpha-2": "PE", "country-code": "604", region: "Americas" },
    { name: "Philippines", "alpha-2": "PH", "country-code": "608", region: "Asia" },
    { name: "Pitcairn", "alpha-2": "PN", "country-code": "612", region: "Oceania" },
    { name: "Poland", "alpha-2": "PL", "country-code": "616", region: "Europe" },
    { name: "Portugal", "alpha-2": "PT", "country-code": "620", region: "Europe" },
    { name: "Puerto Rico", "alpha-2": "PR", "country-code": "630", region: "Americas" },
    { name: "Qatar", "alpha-2": "QA", "country-code": "634", region: "Asia" },
    { name: "Réunion", "alpha-2": "RE", "country-code": "638", region: "Africa" },
    { name: "Romania", "alpha-2": "RO", "country-code": "642", region: "Europe" },
    { name: "Russian Federation", "alpha-2": "RU", "country-code": "643", region: "Europe" },
    { name: "Rwanda", "alpha-2": "RW", "country-code": "646", region: "Africa" },
    { name: "Saint Barthélemy", "alpha-2": "BL", "country-code": "652", region: "Americas" },
    { name: "Saint Helena, Ascension and Tristan da Cunha", "alpha-2": "SH", "country-code": "654", region: "Africa" },
    { name: "Saint Kitts and Nevis", "alpha-2": "KN", "country-code": "659", region: "Americas" },
    { name: "Saint Lucia", "alpha-2": "LC", "country-code": "662", region: "Americas" },
    { name: "Saint Martin (French part)", "alpha-2": "MF", "country-code": "663", region: "Americas" },
    { name: "Saint Pierre and Miquelon", "alpha-2": "PM", "country-code": "666", region: "Americas" },
    { name: "Saint Vincent and the Grenadines", "alpha-2": "VC", "country-code": "670", region: "Americas" },
    { name: "Samoa", "alpha-2": "WS", "country-code": "882", region: "Oceania" },
    { name: "San Marino", "alpha-2": "SM", "country-code": "674", region: "Europe" },
    { name: "Sao Tome and Principe", "alpha-2": "ST", "country-code": "678", region: "Africa" },
    { name: "Saudi Arabia", "alpha-2": "SA", "country-code": "682", region: "Asia" },
    { name: "Senegal", "alpha-2": "SN", "country-code": "686", region: "Africa" },
    { name: "Serbia", "alpha-2": "RS", "country-code": "688", region: "Europe" },
    { name: "Seychelles", "alpha-2": "SC", "country-code": "690", region: "Africa" },
    { name: "Sierra Leone", "alpha-2": "SL", "country-code": "694", region: "Africa" },
    { name: "Singapore", "alpha-2": "SG", "country-code": "702", region: "Asia" },
    { name: "Sint Maarten (Dutch part)", "alpha-2": "SX", "country-code": "534", region: "Americas" },
    { name: "Slovakia", "alpha-2": "SK", "country-code": "703", region: "Europe" },
    { name: "Slovenia", "alpha-2": "SI", "country-code": "705", region: "Europe" },
    { name: "Solomon Islands", "alpha-2": "SB", "country-code": "090", region: "Oceania" },
    { name: "Somalia", "alpha-2": "SO", "country-code": "706", region: "Africa" },
    { name: "South Africa", "alpha-2": "ZA", "country-code": "710", region: "Africa" },
    { name: "South Georgia and the South Sandwich Islands", "alpha-2": "GS", "country-code": "239", region: "Americas" },
    { name: "South Sudan", "alpha-2": "SS", "country-code": "728", region: "Africa" },
    { name: "Spain", "alpha-2": "ES", "country-code": "724", region: "Europe" },
    { name: "Sri Lanka", "alpha-2": "LK", "country-code": "144", region: "Asia" },
    { name: "Sudan", "alpha-2": "SD", "country-code": "729", region: "Africa" },
    { name: "Suriname", "alpha-2": "SR", "country-code": "740", region: "Americas" },
    { name: "Svalbard and Jan Mayen", "alpha-2": "SJ", "country-code": "744", region: "Europe" },
    { name: "Sweden", "alpha-2": "SE", "country-code": "752", region: "Europe" },
    { name: "Switzerland", "alpha-2": "CH", "country-code": "756", region: "Europe" },
    { name: "Syrian Arab Republic", "alpha-2": "SY", "country-code": "760", region: "Asia" },
    { name: "Taiwan, Province of China", "alpha-2": "TW", "country-code": "158", region: "Asia" },
    { name: "Tajikistan", "alpha-2": "TJ", "country-code": "762", region: "Asia" },
    { name: "Tanzania, United Republic of", "alpha-2": "TZ", "country-code": "834", region: "Africa" },
    { name: "Thailand", "alpha-2": "TH", "country-code": "764", region: "Asia" },
    { name: "Timor-Leste", "alpha-2": "TL", "country-code": "626", region: "Asia" },
    { name: "Togo", "alpha-2": "TG", "country-code": "768", region: "Africa" },
    { name: "Tokelau", "alpha-2": "TK", "country-code": "772", region: "Oceania" },
    { name: "Tonga", "alpha-2": "TO", "country-code": "776", region: "Oceania" },
    { name: "Trinidad and Tobago", "alpha-2": "TT", "country-code": "780", region: "Americas" },
    { name: "Tunisia", "alpha-2": "TN", "country-code": "788", region: "Africa" },
    { name: "Turkey", "alpha-2": "TR", "country-code": "792", region: "Asia" },
    { name: "Turkmenistan", "alpha-2": "TM", "country-code": "795", region: "Asia" },
    { name: "Turks and Caicos Islands", "alpha-2": "TC", "country-code": "796", region: "Americas" },
    { name: "Tuvalu", "alpha-2": "TV", "country-code": "798", region: "Oceania" },
    { name: "Uganda", "alpha-2": "UG", "country-code": "800", region: "Africa" },
    { name: "Ukraine", "alpha-2": "UA", "country-code": "804", region: "Europe" },
    { name: "United Arab Emirates", "alpha-2": "AE", "country-code": "784", region: "Asia" },
    { name: "United Kingdom of Great Britain and Northern Ireland", "alpha-2": "GB", "country-code": "826", region: "Europe" },
    { name: "United States of America", "alpha-2": "US", "country-code": "840", region: "Americas" },
    { name: "United States Minor Outlying Islands", "alpha-2": "UM", "country-code": "581", region: "Oceania" },
    { name: "Uruguay", "alpha-2": "UY", "country-code": "858", region: "Americas" },
    { name: "Uzbekistan", "alpha-2": "UZ", "country-code": "860", region: "Asia" },
    { name: "Vanuatu", "alpha-2": "VU", "country-code": "548", region: "Oceania" },
    { name: "Venezuela (Bolivarian Republic of)", "alpha-2": "VE", "country-code": "862", region: "Americas" },
    { name: "Viet Nam", "alpha-2": "VN", "country-code": "704", region: "Asia" },
    { name: "Virgin Islands (British)", "alpha-2": "VG", "country-code": "092", region: "Americas" },
    { name: "Virgin Islands (U.S.)", "alpha-2": "VI", "country-code": "850", region: "Americas" },
    { name: "Wallis and Futuna", "alpha-2": "WF", "country-code": "876", region: "Oceania" },
    { name: "Western Sahara", "alpha-2": "EH", "country-code": "732", region: "Africa" },
    { name: "Yemen", "alpha-2": "YE", "country-code": "887", region: "Asia" },
    { name: "Zambia", "alpha-2": "ZM", "country-code": "894", region: "Africa" },
    { name: "Zimbabwe", "alpha-2": "ZW", "country-code": "716", region: "Africa" },
]